#!/usr/bin/env sh

FORBIDDEN_HTTPS_URL="https://github.com/BSM-Investment-Simulation/Investment_Frontend.git" # insert your remote url (https)
FORBIDDEN_SSH_URL="git@github.com:BSM-Investment-Simulation/Investment_Frontend.git" # insert your remote url (ssh)
FORBIDDEN_REF="refs/heads/main" # insert branch ref

ARR_GIT_PARAMS=($(echo $HUSKY_GIT_PARAMS))
ARR_GIT_STDIN=($(echo $HUSKY_GIT_STDIN))

remote=${ARR_GIT_PARAMS[0]}
url=${ARR_GIT_PARAMS[1]}

local_ref=${ARR_GIT_STDIN[0]}
local_sha=${ARR_GIT_STDIN[1]}
remote_ref=${ARR_GIT_STDIN[2]}
remote_sha=${ARR_GIT_STDIN[3]}

if [ "$url" != "$FORBIDDEN_HTTPS_URL" -a "$url" != "$FORBIDDEN_SSH_URL" ]
then
    exit 0 # Forked Project 에서는 제한하지 않음
fi

if [ "$remote_ref" == "$FORBIDDEN_REF" ]
then
    echo "Pushing into main branch is prohibited."
    exit 1 
fi

exit 0